// AUTO-GENERATED manifest of official ACE Language Centre photographs.
// 102 real photos organised into gallery categories.
export type GalleryCategory =
  | "Campus" | "Classrooms" | "Students" | "Teachers" | "Events"
  | "Graduation" | "Facilities" | "Activities" | "Accommodation";

export type GalleryImage = { src: string; category: GalleryCategory; alt: string };

export const galleryCategories: GalleryCategory[] = [
  "Campus","Classrooms","Students","Teachers","Events","Graduation","Facilities","Activities","Accommodation",
];

export const galleryImages: GalleryImage[] = [
  { src: "/gallery/ace-001.jpg", category: "Campus", alt: "ACE Language Centre campus in Kuala Lumpur (1)" },
  { src: "/gallery/ace-002.jpg", category: "Campus", alt: "ACE Language Centre campus in Kuala Lumpur (2)" },
  { src: "/gallery/ace-003.jpg", category: "Campus", alt: "ACE Language Centre campus in Kuala Lumpur (3)" },
  { src: "/gallery/ace-004.jpg", category: "Campus", alt: "ACE Language Centre campus in Kuala Lumpur (4)" },
  { src: "/gallery/ace-005.jpg", category: "Campus", alt: "ACE Language Centre campus in Kuala Lumpur (5)" },
  { src: "/gallery/ace-006.jpg", category: "Campus", alt: "ACE Language Centre campus in Kuala Lumpur (6)" },
  { src: "/gallery/ace-007.jpg", category: "Campus", alt: "ACE Language Centre campus in Kuala Lumpur (7)" },
  { src: "/gallery/ace-008.jpg", category: "Campus", alt: "ACE Language Centre campus in Kuala Lumpur (8)" },
  { src: "/gallery/ace-009.jpg", category: "Campus", alt: "ACE Language Centre campus in Kuala Lumpur (9)" },
  { src: "/gallery/ace-010.jpg", category: "Campus", alt: "ACE Language Centre campus in Kuala Lumpur (10)" },
  { src: "/gallery/ace-011.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (11)" },
  { src: "/gallery/ace-012.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (12)" },
  { src: "/gallery/ace-013.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (13)" },
  { src: "/gallery/ace-014.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (14)" },
  { src: "/gallery/ace-015.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (15)" },
  { src: "/gallery/ace-016.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (16)" },
  { src: "/gallery/ace-017.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (17)" },
  { src: "/gallery/ace-018.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (18)" },
  { src: "/gallery/ace-019.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (19)" },
  { src: "/gallery/ace-020.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (20)" },
  { src: "/gallery/ace-021.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (21)" },
  { src: "/gallery/ace-022.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (22)" },
  { src: "/gallery/ace-023.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (23)" },
  { src: "/gallery/ace-024.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (24)" },
  { src: "/gallery/ace-025.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (25)" },
  { src: "/gallery/ace-026.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (26)" },
  { src: "/gallery/ace-027.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (27)" },
  { src: "/gallery/ace-028.jpg", category: "Classrooms", alt: "English lesson in progress at ACE Language Centre (28)" },
  { src: "/gallery/ace-029.jpg", category: "Students", alt: "International students at ACE Language Centre (29)" },
  { src: "/gallery/ace-030.jpg", category: "Students", alt: "International students at ACE Language Centre (30)" },
  { src: "/gallery/ace-031.jpg", category: "Students", alt: "International students at ACE Language Centre (31)" },
  { src: "/gallery/ace-032.jpg", category: "Students", alt: "International students at ACE Language Centre (32)" },
  { src: "/gallery/ace-033.jpg", category: "Students", alt: "International students at ACE Language Centre (33)" },
  { src: "/gallery/ace-034.jpg", category: "Students", alt: "International students at ACE Language Centre (34)" },
  { src: "/gallery/ace-035.jpg", category: "Students", alt: "International students at ACE Language Centre (35)" },
  { src: "/gallery/ace-036.jpg", category: "Students", alt: "International students at ACE Language Centre (36)" },
  { src: "/gallery/ace-037.jpg", category: "Students", alt: "International students at ACE Language Centre (37)" },
  { src: "/gallery/ace-038.jpg", category: "Students", alt: "International students at ACE Language Centre (38)" },
  { src: "/gallery/ace-039.jpg", category: "Students", alt: "International students at ACE Language Centre (39)" },
  { src: "/gallery/ace-040.jpg", category: "Students", alt: "International students at ACE Language Centre (40)" },
  { src: "/gallery/ace-041.jpg", category: "Students", alt: "International students at ACE Language Centre (41)" },
  { src: "/gallery/ace-042.jpg", category: "Students", alt: "International students at ACE Language Centre (42)" },
  { src: "/gallery/ace-043.jpg", category: "Students", alt: "International students at ACE Language Centre (43)" },
  { src: "/gallery/ace-044.jpg", category: "Students", alt: "International students at ACE Language Centre (44)" },
  { src: "/gallery/ace-045.jpg", category: "Students", alt: "International students at ACE Language Centre (45)" },
  { src: "/gallery/ace-046.jpg", category: "Students", alt: "International students at ACE Language Centre (46)" },
  { src: "/gallery/ace-047.jpg", category: "Students", alt: "International students at ACE Language Centre (47)" },
  { src: "/gallery/ace-048.jpg", category: "Students", alt: "International students at ACE Language Centre (48)" },
  { src: "/gallery/ace-049.jpg", category: "Students", alt: "International students at ACE Language Centre (49)" },
  { src: "/gallery/ace-050.jpg", category: "Students", alt: "International students at ACE Language Centre (50)" },
  { src: "/gallery/ace-051.jpg", category: "Teachers", alt: "ACE Language Centre teachers with students (51)" },
  { src: "/gallery/ace-052.jpg", category: "Teachers", alt: "ACE Language Centre teachers with students (52)" },
  { src: "/gallery/ace-053.jpg", category: "Teachers", alt: "ACE Language Centre teachers with students (53)" },
  { src: "/gallery/ace-054.jpg", category: "Teachers", alt: "ACE Language Centre teachers with students (54)" },
  { src: "/gallery/ace-055.jpg", category: "Teachers", alt: "ACE Language Centre teachers with students (55)" },
  { src: "/gallery/ace-056.jpg", category: "Teachers", alt: "ACE Language Centre teachers with students (56)" },
  { src: "/gallery/ace-057.jpg", category: "Teachers", alt: "ACE Language Centre teachers with students (57)" },
  { src: "/gallery/ace-058.jpg", category: "Teachers", alt: "ACE Language Centre teachers with students (58)" },
  { src: "/gallery/ace-059.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (59)" },
  { src: "/gallery/ace-060.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (60)" },
  { src: "/gallery/ace-061.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (61)" },
  { src: "/gallery/ace-062.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (62)" },
  { src: "/gallery/ace-063.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (63)" },
  { src: "/gallery/ace-064.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (64)" },
  { src: "/gallery/ace-065.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (65)" },
  { src: "/gallery/ace-066.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (66)" },
  { src: "/gallery/ace-067.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (67)" },
  { src: "/gallery/ace-068.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (68)" },
  { src: "/gallery/ace-069.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (69)" },
  { src: "/gallery/ace-070.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (70)" },
  { src: "/gallery/ace-071.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (71)" },
  { src: "/gallery/ace-072.jpg", category: "Activities", alt: "Student activities at ACE Language Centre (72)" },
  { src: "/gallery/ace-073.jpg", category: "Events", alt: "An event at ACE Language Centre (73)" },
  { src: "/gallery/ace-074.jpg", category: "Events", alt: "An event at ACE Language Centre (74)" },
  { src: "/gallery/ace-075.jpg", category: "Events", alt: "An event at ACE Language Centre (75)" },
  { src: "/gallery/ace-076.jpg", category: "Events", alt: "An event at ACE Language Centre (76)" },
  { src: "/gallery/ace-077.jpg", category: "Events", alt: "An event at ACE Language Centre (77)" },
  { src: "/gallery/ace-078.jpg", category: "Events", alt: "An event at ACE Language Centre (78)" },
  { src: "/gallery/ace-079.jpg", category: "Events", alt: "An event at ACE Language Centre (79)" },
  { src: "/gallery/ace-080.jpg", category: "Events", alt: "An event at ACE Language Centre (80)" },
  { src: "/gallery/ace-081.jpg", category: "Events", alt: "An event at ACE Language Centre (81)" },
  { src: "/gallery/ace-082.jpg", category: "Events", alt: "An event at ACE Language Centre (82)" },
  { src: "/gallery/ace-083.jpg", category: "Events", alt: "An event at ACE Language Centre (83)" },
  { src: "/gallery/ace-084.jpg", category: "Events", alt: "An event at ACE Language Centre (84)" },
  { src: "/gallery/ace-085.jpg", category: "Events", alt: "An event at ACE Language Centre (85)" },
  { src: "/gallery/ace-086.jpg", category: "Graduation", alt: "Graduation and achievement celebration at ACE Language Centre (86)" },
  { src: "/gallery/ace-087.jpg", category: "Graduation", alt: "Graduation and achievement celebration at ACE Language Centre (87)" },
  { src: "/gallery/ace-088.jpg", category: "Graduation", alt: "Graduation and achievement celebration at ACE Language Centre (88)" },
  { src: "/gallery/ace-089.jpg", category: "Graduation", alt: "Graduation and achievement celebration at ACE Language Centre (89)" },
  { src: "/gallery/ace-090.jpg", category: "Graduation", alt: "Graduation and achievement celebration at ACE Language Centre (90)" },
  { src: "/gallery/ace-091.jpg", category: "Graduation", alt: "Graduation and achievement celebration at ACE Language Centre (91)" },
  { src: "/gallery/ace-092.jpg", category: "Graduation", alt: "Graduation and achievement celebration at ACE Language Centre (92)" },
  { src: "/gallery/ace-093.jpg", category: "Graduation", alt: "Graduation and achievement celebration at ACE Language Centre (93)" },
  { src: "/gallery/ace-094.jpg", category: "Graduation", alt: "Graduation and achievement celebration at ACE Language Centre (94)" },
  { src: "/gallery/ace-095.jpg", category: "Graduation", alt: "Graduation and achievement celebration at ACE Language Centre (95)" },
  { src: "/gallery/ace-096.jpg", category: "Facilities", alt: "Modern facilities at ACE Language Centre (96)" },
  { src: "/gallery/ace-097.jpg", category: "Facilities", alt: "Modern facilities at ACE Language Centre (97)" },
  { src: "/gallery/ace-098.jpg", category: "Facilities", alt: "Modern facilities at ACE Language Centre (98)" },
  { src: "/gallery/ace-099.jpg", category: "Facilities", alt: "Modern facilities at ACE Language Centre (99)" },
  { src: "/gallery/ace-100.jpg", category: "Facilities", alt: "Modern facilities at ACE Language Centre (100)" },
  { src: "/gallery/ace-101.jpg", category: "Accommodation", alt: "ACE Language Centre student accommodation (101)" },
  { src: "/gallery/ace-102.jpg", category: "Accommodation", alt: "ACE Language Centre student accommodation (102)" },
];

export const galleryCount = galleryImages.length;
